feat: prisma and nuxt auth added, git precommit hooks added

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -7,6 +7,7 @@ on:
 
 jobs:
   build:
+    if: '!contains(github.event.pull_request.title, "release:")'
     runs-on: ubuntu-latest
 
     permissions:
@@ -31,14 +32,43 @@ jobs:
       - name: Install Dependencies
         run: pnpm install
 
+      - name: Build Artifacts
+        run: pnpm build
+
       # - name: Run Tests
       #   run: pnpm test
 
-      # - name: Lint Code
-      #   run: pnpm lint || echo "Linting failed, but continuing"
+      - name: Lint Code
+        run: pnpm lint || echo "Linting failed, but continuing"
 
-      # - name: Format Code
-      #   run: pnpm format
+      - name: Format Code
+        run: pnpm format
 
-      - name: Build Artifacts
-        run: pnpm build
+      - name: Create Release Pull Request
+        uses: googleapis/release-please-action@v4
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          release-type: node
+          skip-github-release: true
+
+  release:
+    if: 'contains(github.event.pull_request.title, "release")'
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Merge into Main Branch
+        run: |
+          git checkout main
+          git merge develop
+
+      - name: Create Release
+        uses: googleapis/release-please-action@v4
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          release-type: node
+          skip-github-pull-request: true
